### ISSUE TITLE
Please add a `LICENSE` file to this repo

### ISSUE THREAD

**Issue by mbrukman** [cassiozen/TDungeon#1]
Thanks for building and sharing this project with us!

I noticed that according to the [`package.json`](https://github.com/cassiozen/TDungeon/blob/679bca47548b1bf8596600433efc61e659b7b29c/package.json#L11) file, this project is under the ISC license:

https://github.com/cassiozen/TDungeon/blob/679bca47548b1bf8596600433efc61e659b7b29c/package.json#L11

Given this, it would be helpful if there were a `LICENSE` file to clarify this for viewers of the repo at a glance, which would also show the license in the summary box on the right side of the repo. https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/ shows what it looked like previously, it looks slightly different now, but the idea is the same.

You can get a copy of the ISC license here: https://choosealicense.com/licenses/isc/

**Comment by cassiozen** [comment]
Good call, thanks
